apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  instances: {{ .Values.replicas }}
  storage:
    size: {{ .Values.storageSize }}
  bootstrap:
    initdb:
      database: {{ .Values.databaseName }}
      owner: {{ .Values.user }}